packages:
  pacman:
    gui:
      - brave-bin
      - cmake
      - firefox
      - ghostty
      - gparted
      - proton-vpn-gtk-app
      - protonmail-bridge
      - seahorse
      - thunderbird
    cli:
      - 7zip
      - atuin
      - bat
      - chafa # terminal image viewer
      - cuda # needed for whisper and ollama
      - fastfetch
      - ffmpeg
      - fzf
      - git
      - git-delta
      - github-cli
      - go-yq
      - imagemagick
      - ncdu
      - neovim
      - nushell
      - ollama-cuda
      - podman
      - poppler
      - qpdf
      - ripgrep
      - sd
      - starship
      - stow
      - tesseract # OCR engine
      - tesseract-data-eng
      - tree
      - uv # Python package and project manager
      - yazi
      - zellij
      - zoxide
    system:
      - btop
      - flatpak
      - gnome-keyring
      - gvfs-smb # required for COSMIC Files to detect SMB
      - htop
      - hunspell-de # German dictionary for spell checking
      - hunspell-en_us
      - hunspell-ru # Russian dictionary for spell checking
      - jq
      - libsecret
      - limine # modern bootloader
      - limine-mkinitcpio-hook # mkinitcpio hook for Limine
      - limine-snapper-sync # Snapper sync script for Limine
      - perl-image-exiftool
      - snap-pac # pacman hook for automatic snapshots with Snapper
      - snapper # Btrfs snapshot management tool
      - wl-clipboard # clipboard support for Wayland. Commands: wl-copy and wl-paste
      - wtype # simulate keyboard input on Wayland
      - xdg-desktop-portal-gtk # required for Flatpak apps to smoothly work on GTK-based desktops
    fonts:
      - ttf-fira-code
      - ttf-jetbrains-mono
      - ttf-jetbrains-mono-nerd

  aur:
    # ALWAYS REVIEW PKGBUILD FILES!
    gui:
      # MARK: translateSelection with Crow and Wayland doesn't work well for now
      # - crow-translate
      - proton-pass-bin
      - visual-studio-code-bin
      - webapp-manager # run websites as apps
    cli:
      - carapace-bin

  flatpak:
    - com.calibre_ebook.calibre
    - com.github.tchx84.Flatseal
    - com.github.xournalpp.xournalpp
    - com.obsproject.Studio
    - com.spotify.Client
    - io.github.cosmic_utils.minimon-applet # system monitor applet for COSMIC
    - io.podman_desktop.PodmanDesktop
    - md.obsidian.Obsidian
    - org.gimp.GIMP
    - org.inkscape.Inkscape
    - org.libreoffice.LibreOffice
    - org.localsend.localsend_app
    - org.shotcut.Shotcut
    - org.videolan.VLC
    - rest.insomnia.Insomnia
